import 'meal_feedback_catalog.dart';

const mealFeedbackExtras = <String, MealFeedback>{
  'arroz, feijão, frango e legumes': MealFeedback('Refeição completa com vegetais', 'positive', 'O arroz fornece carboidratos, o feijão contribui com fibras e nutrientes, o frango acrescenta proteína e os legumes aumentam a variedade de vegetais.', 'Varie os legumes e observe as porções e a quantidade de óleo usada no preparo.'),
  'arroz, carne e salada': MealFeedback('Boa combinação para uma refeição', 'positive', 'O arroz fornece carboidratos, a carne acrescenta proteína e a salada contribui com vegetais e fibras.', 'Varie as verduras e legumes e ajuste as porções ao restante da refeição.'),
  'feijão, frango e salada': MealFeedback('Boa combinação com fibras e proteína', 'positive', 'O feijão contribui com fibras e nutrientes, o frango fornece proteína e a salada amplia a presença de vegetais.', 'Acrescente uma fonte de carboidrato conforme o restante da refeição e varie os vegetais.'),
  'batata, frango e legumes': MealFeedback('Refeição variada', 'positive', 'A batata fornece carboidratos, o frango acrescenta proteína e os legumes aumentam a variedade de vegetais e fibras.', 'Prefira preparações com menos óleo e varie os legumes ao longo da semana.'),
  'arroz, ovo e legumes': MealFeedback('Boa base com vegetais', 'positive', 'O arroz fornece carboidratos, o ovo acrescenta proteína e os legumes aumentam a variedade de vegetais e fibras da refeição.', 'Varie os legumes e considere incluir feijão ou outra fonte de fibras em outras refeições.'),
  'arroz, feijão e ovo': MealFeedback('Combinação com proteína e fibras', 'positive', 'O arroz fornece carboidratos, o feijão contribui com fibras e o ovo acrescenta proteína à refeição.', 'Varie os vegetais e observe as porções e o modo de preparo.'),
  'arroz, feijão e carne': MealFeedback('Base tradicional equilibrada', 'positive', 'O arroz fornece carboidratos, o feijão acrescenta fibras e a carne fornece proteína.', 'Inclua verduras ou legumes para aumentar a variedade de vegetais da refeição.'),
  'arroz, frango e salada': MealFeedback('Combinação simples e variada', 'positive', 'O arroz fornece carboidratos, o frango fornece proteína e a salada acrescenta vegetais e fibras.', 'Varie as verduras e legumes e ajuste as porções ao restante do dia.'),
  'feijão, carne e legumes': MealFeedback('Boa combinação de proteína, fibras e vegetais', 'positive', 'O feijão contribui com fibras e nutrientes, a carne fornece proteína e os legumes aumentam a presença de vegetais.', 'Varie os legumes e considere uma fonte de carboidrato conforme o restante da refeição.'),
  'macarrão, frango e legumes': MealFeedback('Refeição com carboidrato, proteína e vegetais', 'positive', 'O macarrão fornece carboidratos, o frango acrescenta proteína e os legumes aumentam a variedade de vegetais.', 'Prefira preparações com quantidade moderada de óleo e molhos e varie os legumes.'),
};
