import '../models/meal_feedback.dart';

const mealFeedbackBatch08 = <String, MealFeedback>{
  'bife acebolado, arroz, feijão e batata frita': MealFeedback('Prato de restaurante mais denso', 'attention', 'O arroz e o feijão formam uma base tradicional, enquanto o bife acrescenta proteína. A batata frita aumenta bastante a densidade energética e de gordura da refeição.', 'Mantenha a salada ou legumes no prato e ajuste a porção de fritas conforme o restante do dia.'),
  'frango à parmegiana, arroz e batata frita': MealFeedback('Parmegiana com bastante energia', 'attention', 'O frango fornece proteína, mas empanado, queijo, molho e batata frita tornam essa combinação mais densa em energia e gordura.', 'Uma salada ou legumes ajudam a aumentar o volume e a variedade; em outras refeições, prefira preparações menos gordurosas.'),
  'strogonoff, arroz e batata palha': MealFeedback('Clássico de restaurante com atenção às porções', 'attention', 'O arroz fornece carboidratos e o strogonoff acrescenta proteína, mas o creme e a batata palha deixam a refeição mais concentrada em energia e gordura.', 'Inclua vegetais ou salada e mantenha uma porção moderada de batata palha.'),
  'x-tudo, batata frita e refrigerante': MealFeedback('Combo de lanchonete bem denso', 'important', 'O X-tudo reúne pão, carne, queijo, embutidos e molhos; com batata frita e refrigerante, a refeição concentra energia, gordura, sódio e açúcar.', 'Se esse combo for ocasional, não precisa transformar uma refeição em culpa. Para equilibrar o dia, priorize água, vegetais e refeições menos processadas nas próximas ocasiões.'),
  'temaki, hot roll e refrigerante': MealFeedback('Combo japonês com pontos de atenção', 'attention', 'O temaki pode oferecer peixe e arroz, mas o hot roll costuma ser frito e o refrigerante acrescenta açúcar sem contribuir muito para a saciedade.', 'Prefira água ou uma bebida sem açúcar e alterne itens fritos com sushi, sashimi ou outras opções menos fritas.'),
};
