import '../models/meal_feedback.dart';

const mealFeedbackBatch08 = <String, MealFeedback>{
  'bife acebolado, arroz, feijão e batata frita': MealFeedback('Prato de restaurante mais denso', 'attention', 'O arroz e o feijão formam uma base tradicional, enquanto o bife acrescenta proteína. A batata frita aumenta bastante a densidade energética e de gordura da refeição.', 'Mantenha a salada ou legumes no prato e ajuste a porção de fritas conforme o restante do dia.'),
  'frango à parmegiana, arroz e batata frita': MealFeedback('Parmegiana com bastante energia', 'attention', 'O frango fornece proteína, mas empanado, queijo, molho e batata frita tornam essa combinação mais densa em energia e gordura.', 'Uma salada ou legumes ajudam a aumentar o volume e a variedade; em outras refeições, prefira preparações menos gordurosas.'),
  'strogonoff, arroz e batata palha': MealFeedback('Clássico de restaurante com atenção às porções', 'attention', 'O arroz fornece carboidratos e o strogonoff acrescenta proteína, mas o creme e a batata palha deixam a refeição mais concentrada em energia e gordura.', 'Inclua vegetais ou salada e mantenha uma porção moderada de batata palha.'),
  'x-tudo, batata frita e refrigerante': MealFeedback('Combo de lanchonete bem denso', 'important', 'O X-tudo reúne pão, carne, queijo, embutidos e molhos; com batata frita e refrigerante, a refeição concentra energia, gordura, sódio e açúcar.', 'Se esse combo for ocasional, não precisa transformar uma refeição em culpa. Para equilibrar o dia, priorize água, vegetais e refeições menos processadas nas próximas ocasiões.'),
  'temaki, hot roll e refrigerante': MealFeedback('Combo japonês com pontos de atenção', 'attention', 'O temaki pode oferecer peixe e arroz, mas o hot roll costuma ser frito e o refrigerante acrescenta açúcar sem contribuir muito para a saciedade.', 'Prefira água ou uma bebida sem açúcar e alterne itens fritos com sushi, sashimi ou outras opções menos fritas.'),
  'feijoada completa, arroz, couve e farofa': MealFeedback('Feijoada completa e tradicional', 'attention', 'A feijoada combina leguminosas e carnes, enquanto arroz, couve e farofa completam o prato. A variedade é boa, mas carnes suínas, farofa e porções grandes podem elevar bastante gordura, sódio e energia.', 'Mantenha a couve e o feijão, controle a porção de farofa e carnes mais gordurosas e prefira água ou bebida sem açúcar.'),
  'escondidinho de carne seca, arroz e salada': MealFeedback('Escondidinho com bom contraste de grupos', 'attention', 'A carne seca fornece proteína, mas pode ter bastante sódio. O purê e o arroz concentram carboidratos, enquanto a salada melhora a presença de vegetais na refeição.', 'A salada é uma boa aliada; controle a quantidade de arroz e observe o sódio quando a carne seca aparecer com frequência.'),
  'cuscuz nordestino, carne de sol, queijo coalho e vinagrete': MealFeedback('Prato regional rico e saboroso', 'attention', 'O cuscuz oferece carboidratos e a carne de sol e o queijo coalho fornecem proteína, mas os dois últimos podem concentrar sódio e gordura.', 'Combine com o vinagrete, ajuste a porção de queijo e carne e varie com fontes de proteína menos salgadas ao longo da semana.'),
  'yakisoba de carne com legumes': MealFeedback('Yakisoba com vegetais, mas atenção ao molho', 'attention', 'A carne contribui com proteína e os legumes aumentam a variedade, porém macarrão e molho de soja podem elevar a carga de carboidratos e sódio da preparação.', 'Valorize a quantidade de legumes e peça menos molho quando possível, especialmente se essa preparação aparecer com frequência.'),
  'hamburguer artesanal, batata rústica e molho': MealFeedback('Combo artesanal ainda é uma refeição densa', 'attention', 'O hambúrguer fornece proteína, mas pão, queijo, molho e batata rústica aumentam energia e gordura da refeição.', 'Acrescente vegetais quando disponíveis e ajuste a porção de batata e molhos; uma bebida sem açúcar ajuda a reduzir açúcar líquido.'),
};
